<a href="https://colab.research.google.com/github/purvilmehta06/Deep-Learning/blob/master/Lab%202/LabAssignment2_201701073.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2: Deep Learning


*   Lab Manual: [Manual Lab 2](https://github.com/purvilmehta06/Deep-Learning/blob/master/Lab%202/Lab_Assignment_2.pdf)
*   Author: Purvil Mehta
*   Id : 201701073
* Github Link : [Deep Learning Course Lab Work Repo](https://github.com/purvilmehta06/Deep-Learning)



# Some of the General Function to implement NN

## Solve function to handle different activation funtion

In [ ]:
def solve(method,weight1,weight2,weight3,weight4,bias1,bias2,bias3,bias4,result):
  if (method=="Relu"):
    layer1_actOutput = tf.nn.relu(neuralNetwork(weight1,bias1,result))
    layer2_actOutput = tf.nn.relu(neuralNetwork(weight2,bias2,layer1_actOutput))
    layer3_actOutput = tf.nn.relu(neuralNetwork(weight3,bias3,layer2_actOutput))
    output = tf.nn.relu(neuralNetwork(weight4,bias4,layer3_actOutput))
  elif (method=="Softmax"):
    layer1_actOutput = tf.nn.softmax(neuralNetwork(weight1,bias1,result))
    layer2_actOutput = tf.nn.softmax(neuralNetwork(weight2,bias2,layer1_actOutput))
    layer3_actOutput = tf.nn.softmax(neuralNetwork(weight3,bias3,layer2_actOutput))
    output = tf.nn.softmax(neuralNetwork(weight4,bias4,layer3_actOutput))
  elif (method=="tanH"):
    layer1_actOutput = tf.nn.tanh(neuralNetwork(weight1,bias1,result))
    layer2_actOutput = tf.nn.tanh(neuralNetwork(weight2,bias2,layer1_actOutput))
    layer3_actOutput = tf.nn.tanh(neuralNetwork(weight3,bias3,layer2_actOutput))
    output = tf.nn.tanh(neuralNetwork(weight4,bias4,layer3_actOutput))
  else:
    layer1_actOutput = tf.nn.sigmoid(neuralNetwork(weight1,bias1,result))
    layer2_actOutput = tf.nn.sigmoid(neuralNetwork(weight2,bias2,layer1_actOutput))
    layer3_actOutput = tf.nn.sigmoid(neuralNetwork(weight3,bias3,layer2_actOutput))
    output = tf.nn.sigmoid(neuralNetwork(weight4,bias4,layer3_actOutput))

  return output

## Generalise Neural Network Code

In [ ]:
def neuralNetwork(weight,bias,data):
  output = tf.add(tf.matmul(weight,data,transpose_a=True) ,bias)
  return output

## NN Weight and Bias Initialisation

In [ ]:
def init(layerOneNode,layerTwoNode,layerThreeNode,batchSize):
  weight1 = tf.random.normal([data.shape[0],layerOneNode], mean=0.0, stddev=0.4, dtype=tf.float32,seed=1)
  weight2 = tf.random.normal([layerOneNode,layerTwoNode], mean=0.0, stddev=0.4, dtype=tf.float32,seed=1)
  weight3 = tf.random.normal([layerTwoNode,layerThreeNode], mean=0.0, stddev=0.4, dtype=tf.float32,seed=1)
  weight4 = tf.random.normal([layerThreeNode,layerThreeNode], mean=0.0, stddev=0.4, dtype=tf.float32,seed=1)

  bias1 = tf.random.normal([layerOneNode,1],mean=0.0, stddev=0.4,seed=1,dtype=tf.float32,)
  bias1 = tf.repeat(bias1, repeats=batchSize,axis=1)

  bias2 = tf.random.normal([layerTwoNode,1],mean=0.0, stddev=0.4,seed=1,dtype=tf.float32,)
  bias2 = tf.repeat(bias2, repeats=batchSize,axis=1)

  bias3 = tf.random.normal([layerThreeNode,1],mean=0.0, stddev=0.4,seed=1,dtype=tf.float32,)
  bias3 = tf.repeat(bias3, repeats=batchSize,axis=1)

  bias4 = tf.random.normal([layerThreeNode,1],mean=0.0, stddev=0.4,seed=1,dtype=tf.float32,)
  bias4 = tf.repeat(bias4, repeats=batchSize,axis=1)
  return weight1,weight2,weight3,weight4,bias1,bias2,bias3,bias4

#MNIST Dataset

## Data Loading from Keras

In [ ]:
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data(path="mnist.npz")
data = tf.Variable(x_train,dtype=tf.float32)
data = tf.reshape(data,[60000,784])
data = tf.transpose(data)

11493376/11490434 [==============================] - 0s 0us/step


## Implementation on NN with diffirent Activation Function and confusion matrix

In [ ]:
layerOneNode = 10
layerTwoNode = 10
layerThreeNode = 10
batchSize = 300 #divisible by 60,000
totalIteration = data.shape[1]//batchSize
Activation_function = ['Relu','Softmax','tanH','Sigmoid'];

for k in range(len(Activation_function)):
  #calculate weight and bias on random basis
  [weight1,weight2,weight3,weight4,bias1,bias2,bias3,bias4]= init(layerOneNode,layerTwoNode,layerThreeNode,batchSize)

  for i in range(1,totalIteration+1):

    #Slicing the data matrix into batch size [0-299,300-599 and so on]
    ind = tf.range(batchSize*(i-1), batchSize*i, 1) 
    result = tf.transpose(tf.nn.embedding_lookup(tf.transpose(data), ind))
    output = solve(Activation_function[k],weight1,weight2,weight3,weight4,bias1,bias2,bias3,bias4,result)
    #deciding what is the predicted output
    if (i==1):
      final = tf.math.argmax(tf.transpose(output),1)
    else:
      final = tf.concat([final, tf.math.argmax(tf.transpose(output),1)], 0)
    
  #Generating Confusion Matrix  
  conf_matrix = tf.math.confusion_matrix(y_train,final)
  print(conf_matrix)
  cnt = 0
  for i in range(10):
    cnt = cnt + conf_matrix[i][i]

  accuracy = [cnt/600]
  tf.print("Accuracy in ["+str(Activation_function[k])+"] is",cnt/600)  

tf.Tensor(
[[   0   91  104  132    0    0    0    0    1 5595]
 [   0   59  105   49    0    0    0    0    0 6529]
 [   0  415  552  383    0    0    0    0    3 4605]
 [   0   58  304  167    0    0    0    0    0 5602]
 [   0 1036  509   95    0    0    0    0    0 4202]
 [   0  189  256  210    0    0    0    0    0 4766]
 [   0  642  130   43    0    0    0    0    1 5102]
 [   0  522  288   50    0    0    0    0    1 5404]
 [   0  102  134  120    0    0    0    0    0 5495]
 [   0  794  498  127    0    0    0    0    0 4530]], shape=(10, 10), dtype=int32)
Accuracy in [Relu] is 8.8466666666666658
tf.Tensor(
[[ 396 4931    3   91   25    0  280  123    9   65]
 [ 472 5925    3   36   40    0  161  105    0    0]
 [ 378 4850  193  104   25    0  158  136  105    9]
 [ 385 5171   72   76   25    0  157   78   49  118]
 [ 414 5099   11   23   26    0  150  116    2    1]
 [ 404 4666   56   46   25    0  117   95    1   11]
 [ 363 5012  182   35   27    1  150  138    3    7]
 [ 43

## Combination of all


In [ ]:
layerOneNode = 10
layerTwoNode = 10
layerThreeNode = 10
batchSize = 600 #divisible by 60,000
totalIteration = data.shape[1]//batchSize

#calculate weight and bias on random basis
[weight1,weight2,weight3,weight4,bias1,bias2,bias3,bias4]= init(layerOneNode,layerTwoNode,layerThreeNode,batchSize)

for i in range(1,totalIteration+1):

  #Slicing the data matrix into batch size [0-299,300-599 and so on]
  ind = tf.range(batchSize*(i-1), batchSize*i, 1) 
  result = tf.transpose(tf.nn.embedding_lookup(tf.transpose(data), ind))

  #Layer 3 implementation with RELU activation function
  layer1_actOutput = tf.nn.relu(neuralNetwork(weight1,bias1,result))
  layer2_actOutput = tf.nn.tanh(neuralNetwork(weight2,bias2,layer1_actOutput))
  layer3_actOutput = tf.nn.relu(neuralNetwork(weight3,bias3,layer2_actOutput))
  output = tf.nn.sigmoid(neuralNetwork(weight4,bias4,layer3_actOutput))
  
  #deciding what is the predicted output
  if (i==1):
    final = tf.math.argmax(tf.transpose(output),1)
  else:
    final = tf.concat([final, tf.math.argmax(tf.transpose(output),1)], 0)
  
#Generating Confusion Matrix  
conf_matrix = tf.math.confusion_matrix(y_train,final)
print(conf_matrix)
cnt = 0
for i in range(10):
  cnt = cnt + conf_matrix[i][i]

accuracy = [cnt/600]
tf.print("Accuracy : ",cnt/600)  

tf.Tensor(
[[1855   66 1977    0  134  176    0  801  914    0]
 [ 681    9 5011    0  454   24    0  172  391    0]
 [1112   29 1540    0  118   75    0 2946  138    0]
 [ 729    7 3612    0  346  486    0  760  191    0]
 [ 555   28 1850    1  164   44    0 2990  210    0]
 [ 661   39 2753    1  504  308    0  814  340    1]
 [ 467   43 1378    0  305   22    0 3619   84    0]
 [ 616   31 2409    0  210  118    0 2776  105    0]
 [ 450   15 3413    0  535  224    0  960  254    0]
 [1013   33 2266    1  345  105    0 1779  407    0]], shape=(10, 10), dtype=int32)
Accuracy :  11.51


## Analysis based on different Batch Size

Here I have assumed the activation fuction as "Sigmoid". 

In [ ]:
layerOneNode = 10
layerTwoNode = 10
layerThreeNode = 10
batchSize = [200,300,600] #divisible by 60,000


for i in range(len(batchSize)):
  #calculate weight and bias on random basis
  [weight1,weight2,weight3,weight4,bias1,bias2,bias3,bias4]= init(layerOneNode,layerTwoNode,layerThreeNode,batchSize[i])
  
  totalIteration = data.shape[1]//batchSize[i]
  for j in range(1,totalIteration+1):

    #Slicing the data matrix into batch size [0-299,300-599 and so on]
    ind = tf.range(batchSize[i]*(j-1), batchSize[i]*j, 1) 
    result = tf.transpose(tf.nn.embedding_lookup(tf.transpose(data), ind))

    #Layer 3 implementation with RELU activation function
    layer1_actOutput = tf.nn.sigmoid(neuralNetwork(weight1,bias1,result))
    layer2_actOutput = tf.nn.sigmoid(neuralNetwork(weight2,bias2,layer1_actOutput))
    layer3_actOutput = tf.nn.sigmoid(neuralNetwork(weight3,bias3,layer2_actOutput))
    output = tf.nn.sigmoid(neuralNetwork(weight4,bias4,layer3_actOutput))
    
    #deciding what is the predicted output
    if (j==1):
      final = tf.math.argmax(tf.transpose(output),1)
    else:
      final = tf.concat([final, tf.math.argmax(tf.transpose(output),1)], 0)
    
  #Generating Confusion Matrix  
  conf_matrix = tf.math.confusion_matrix(y_train,final)
  cnt = 0
  for k in range(10):
    cnt = cnt + conf_matrix[k][k]
  tf.print("Accuracy in batch Size : [" + str(batchSize[i]) + "] is",cnt/600)

Accuracy in batch Size : [200] is 9.8716666666666661
Accuracy in batch Size : [300] is 9.93
Accuracy in batch Size : [600] is 9.93


#Boston Housing Dataset

## Data Loading from Keras

In [ ]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.boston_housing.load_data(path='boston_housing.npz')

57344/57026 [==============================] - 0s 0us/step


In [ ]:
data = tf.Variable(x_train,dtype=tf.float32)
data = tf.transpose(data)

## Implementation on Diffirent Activation Function Activation Function 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import math 
layerOneNode = 5
layerTwoNode = 5
layerThreeNode = 1
batchSize = [101,202] #divisible by 404
Activation_function = ['Relu','Softmax','Sigmoid'];

for i in range(len(batchSize)):

  for k in range(len(Activation_function)):
    #calculate weight and bias on random basis
    [weight1,weight2,weight3,weight4,bias1,bias2,bias3,bias4]= init(layerOneNode,layerTwoNode,layerThreeNode,batchSize[i])
    
    totalIteration = data.shape[1]//batchSize[i]
    for j in range(1,totalIteration+1):

      #Slicing the data matrix into batch size [0-299,300-599 and so on]
      ind = tf.range(batchSize[i]*(j-1), batchSize[i]*j, 1) 
      result = tf.transpose(tf.nn.embedding_lookup(tf.transpose(data), ind))

      output = solve(Activation_function[k],weight1,weight2,weight3,weight4,bias1,bias2,bias3,bias4,result)
      #deciding what is the predicted output
      if (j==1):
        final = tf.transpose(output)
      else:
        final = tf.concat([final, tf.transpose(output)], 0)
      

    MSE = math.sqrt(tf.math.reduce_sum((final - y_train)**2))
    tf.print("MSE in batch Size : [" + str(batchSize[i]) + "] and activation function [" + str(Activation_function[k]) + "] is",MSE)


MSE in batch Size : [101] and activation function [Relu] is 9781.143491432891
MSE in batch Size : [101] and activation function [Softmax] is 9777.443428626933
MSE in batch Size : [101] and activation function [Sigmoid] is 9637.688934594227
MSE in batch Size : [202] and activation function [Relu] is 11672.017820411345
MSE in batch Size : [202] and activation function [Softmax] is 9779.293225995425
MSE in batch Size : [202] and activation function [Sigmoid] is 9624.418943499913


## Analysis

Since we are not propogating backward and calculating weights and bias, it is obvious to have very low accuracy. 

In the first problem, I tried two approaches.
1. Fixed batch size and different activation 
2. Fixed activation and different batch size 

In both, we found nearly same accuracy.

In the second problem, I tried three activation fuction on two different batch size and found the same result. 